# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6fa4878811f7e81b7a440c81e14b6c09c254b2a25c0de422e9c1b311df4a9923ec7c5e330d0aca8b1d8f716944747ec557a5f3cebc54cb1813a5ea4736119f4

test:
  secret_key_base: f395d01baa21b61ea6e12d2b1fa1f2f89c2fc602184ba13fdee1a990e6ddc534fb7990f1f48e8aee9bfbcc747305a129c35687ade54d017201335542e05e4e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
